.. image:: /images/hpe_logo2.png
   :width: 150pt
   
|

If not created already,  create an instance of Rest or Redfish Object using the  **RestObject** or **RedfishObject** class respectively. The class constructor takes iLO hostname/ ip address, iLO login username and password as arguments. The class also initializes a login session, gets systems resources and message registries.

Rest Object creation:

.. code-block:: python

 REST_OBJ = RestObject(iLO_host, login_account, login_password)

::

Redfish Object creation:

.. code-block:: python

 REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)

::



Example 15: Set UID light
=========================

The method **ex15_set_uid_light** takes an instance of rest object (or redfish object if using Redfish API) and  boolean uid state (FALSE for turn off  or TRUE for turn on) as arguments.


.. code-block:: python


    def ex15_set_uid_light(restobj, uid):

::


Find and get the system resource for computer system. 

.. code-block:: python


     instances = restobj.search_for_type("ComputerSystem.")

::



Prepare the PATCH request header based on the requested UID state parameter.

.. code-block:: python

        for instance in instances:
           body = dict()
           if uid:
             body["IndicatorLED"] = "Lit"
           else:
             body["IndicatorLED"] = "Off"


::

Perform the PATCH action, check the response.

.. code-block:: python

        response = restobj.rest_patch(instance["href"], body)
        restobj.error_handler(response)

::
 
 