.. image:: /images/hpe_logo2.png
   :width: 150pt
   
|



First create an instance of Rest or Redfish Object using the  **RestObject** or **RedfishObject** class respectively. The class constructor takes iLO hostname/ ip address formatted as a string ("https://xx.xx.xx.xx"), iLO login username and password as arguments. The class also initializes a login session, gets systems resources and message registries.

Rest Object creation:

.. code-block:: python

 REST_OBJ = RestObject(iLO_https_host, login_account, login_password)

::

Redfish Object creation:

.. code-block:: python

 REDFISH_OBJ = RedfishObject(iLO_https_host, login_account, login_password)

::



Example 18: Set server asset tag
================================

The method **ex18_set_server_asset_tag** takes an instance of rest object ( or redfish object if using Redfish API ) and asset tag to be set as arguments.


.. code-block:: python


    def ex18_set_server_asset_tag(restobj, asset_tag):


::


Find and get the system resource for computer system. 

.. code-block:: python


     instances = restobj.search_for_type("ComputerSystem.")

::


For each system for the systems collection asset tag parameter is set as the body for PATCH request.



.. code-block:: python

           for instance in instances:
               body = {"AssetTag": asset_tag}

::



The PATCH request is performed with the asset tag in the body.

.. code-block:: python

        response = restobj.rest_patch(instance["href"], body)
        restobj.error_handler(response)

::