.. image:: /images/hpe_logo2.png
   :width: 150pt
   
|



First create an instance of Rest or Redfish Object using the  **RestObject** or **RedfishObject** class respectively. The class constructor takes iLO hostname/ ip address formatted as a string ("https://xx.xx.xx.xx"), iLO login username and password as arguments. The class also initializes a login session, gets systems resources and message registries.

Rest Object creation:

.. code-block:: python

 REST_OBJ = RestObject(iLO_https_host, login_account, login_password)

::

Redfish Object creation:

.. code-block:: python

 REDFISH_OBJ = RedfishObject(iLO_https_host, login_account, login_password)

::

Example 22: Dump Integrated Management Log
==========================================

The method **def ex22_dump_iml** takes an instance of rest object ( or redfish object if using Redfish API ) as argument.

.. code-block:: python


  def ex22_dump_iml(restobj):

::


Find and get the system resource for log service. 

.. code-block:: python


     instances = restobj.search_for_type("LogService.")

::

Send HTTP GET request to log service IML URI(s).

.. code-block:: python

     for instance in instances:
        if instance["href"].endswith("IML"):
            tmp = restobj.rest_get(instance["href"])

::

Send another GET request to IML entries URI.

.. code-block:: python

        for entry in tmp.dict["links"]["Entries"]:
            response = restobj.rest_get(entry["href"])
::




From the IML entries link response print log entry.

.. code-block:: python

 for log_entry in response.dict["Items"]:
     sys.stdout.write(log_entry["Severity"] + ": Class " + \
                      str(log_entry["Oem"]["Hp"]["Class"]) + \
                      " / Code " + str(log_entry["Oem"]["Hp"]["Code"]) + \
                      ":\t" + log_entry["Message"] + "\n")

::