.. image:: /images/hpe_logo2.png
   :width: 150pt
   
|


If not created already,  create an instance of Rest or Redfish Object using the  **RestObject** or **RedfishObject** class respectively. The class constructor takes iLO hostname/ ip address, iLO login username and password as arguments. The class also initializes a login session, gets systems resources and message registries.

Rest Object creation:

.. code-block:: python

 REST_OBJ = RestObject(iLO_host, login_account, login_password)

::

Redfish Object creation:

.. code-block:: python

 REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)

::

Example 23: Get iLO Event Log
=============================

The method **ex23_dump_ilo_event_log** takes an instance of rest object ( or redfish object if using Redfish API ) as argument.

.. code-block:: python

  def ex23_dump_ilo_event_log(restobj):

::

Find and get the system resource for log service. 

.. code-block:: python


     instances = restobj.search_for_type("LogService.")

::

Send HTTP GET request to log service IEL URI(s).

.. code-block:: python

     for instance in instances:
        if instance["href"].endswith("IEL"):
            tmp = restobj.rest_get(instance["href"])
::

Send another GET request to IEL entries URI.

.. code-block:: python

        for entry in tmp.dict["links"]["Entries"]:
            response = restobj.rest_get(entry["href"])
::




From the IEL entries link response print log entry messages.

.. code-block:: python

        for log_entry in response.dict["Items"]:
            sys.stdout.write(log_entry["Message"] + "\n")

::