.. image:: /images/hpe_logo2.png
   :width: 150pt
   
|

If not created already,  create an instance of Rest or Redfish Object using the  **RestObject** or **RedfishObject** class respectively. The class constructor takes iLO hostname/ ip address, iLO login username and password as arguments. The class also initializes a login session, gets systems resources and message registries.

Rest Object creation:

.. code-block:: python

 REST_OBJ = RestObject(iLO_host, login_account, login_password)

::

Redfish Object creation:

.. code-block:: python

 REDFISH_OBJ = RedfishObject(iLO_host, login_account, login_password)

::


Example 19: Reset iLO
================================

The method **ex19_reset_ilo** takes an instance of rest object( or redfish object if using Redfish API)  as argument.


.. code-block:: python


    def ex19_reset_ilo(restobj):


::


Find and get the system resource for manager. 

.. code-block:: python


     instances = restobj.search_for_type("Manager.")

::



Action reset request is added for the POST request body.

.. code-block:: python

   for instance in instances:
        body = {"Action": "Reset"}

::
  
POST request for iLO reset is performed and response status is checked.

.. code-block:: python

        response = restobj.rest_post(instance["href"], body)
        restobj.error_handler(response)

::